-- 0021: 2FA（TOTP）与 TGBot 绑定列
ALTER TABLE users ADD COLUMN IF NOT EXISTS totp_secret TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS totp_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tg_chat_id TEXT;
CREATE INDEX IF NOT EXISTS users_tg_bound ON users (tg_chat_id) WHERE tg_chat_id IS NOT NULL;
